AuScope/ANVGL-Portal

- pom.xml
- src/main/webapp/WEB-INF/applicationContext.xml
- vm/cloud.sh
Adds s3/ec2 versions of the cloudcompute/cloudstorage services. Updates cloud.sh to use the current version of aws CLI
Don't pull this in until the associated PR at portal core has been accepted
> ANVGL-3 Updates to Storage/Compute to support AWS

- src/main/resources/config.properties
A simple fix to use placeholders for DB{HOST,PORT,NAME} in the properties for the default deployment that is used by the AWS cloud formation script.
> Correct placeholders in DB endpoint for aws deployment.

- src/main/java/org/auscope/portal/server/vegl/VGLJobStatusAndLogReader.java
- src/main/java/org/auscope/portal/server/web/controllers/JobBuilderController.java
- src/main/java/org/auscope/portal/server/web/service/monitor/VGLJobStatusChangeHandler.java
- src/main/resources/org/auscope/portal/server/web/controllers/vl-cloudformation.json.tpl
- src/test/java/org/auscope/portal/server/vegl/TestVGLJobStatusAndLogReader.java
Don't pull this until https://github.com/AuScope/portal-core/pull/143 is in (it won't compile)
I've improved the getJobStatus method by adding a "GetJobStatus" check to the CloudComputeService. This check is used in the situation where we have no uploaded files to verify the "Pending" status of the job. In this scenario we go to the cloud and ask us for more information about the machine status.
> ANVGL-70 More robust job VM status checking

- src/main/resources/org/auscope/portal/server/web/controllers/vl-provisioning.sh
Updated the vl-provisioning script to use /root/anvglmodules instead of /tmp/modules for the puppet modules when provisioning a job VM. Should avoid the /tmp shenanigans on bootstrap.
> Clone puppet modules into /root (ANVGL-109)

- src/main/webapp/js/vegl/JobList.js
ANVGL-118 accidently reverted ANVGL-97 refreshing. This reapplies it to the new tree panel
> ANVGL-97 Reapplied timed refresh to treepanel

- src/main/resources/org/auscope/portal/server/web/controllers/vl-cloudformation.json.tpl
Added output descriptions to the cloudformation template, so that the STS role and the S3 instance profile ARNs are returned. The values can be retrieved from the Outputs tab in the CF console, or returned when using the command line tools.
> ANVGL-102: Return storage and compute ARNs from CF template

- src/main/java/org/auscope/portal/server/web/controllers/JobListController.java
- src/main/webapp/js/vegl/JobList.js
- src/main/webapp/js/vegl/widgets/JobDetailsPanel.js
- src/main/webapp/js/vegl/widgets/JobsTree.js
Two changes suggested by Carsten:
Periodic status requests only return status values. Those values are merged into the existing stores.
The details panel also updated with new status values for currently selected jobs
> ANVGL-97 Improved status updating

- src/main/java/org/auscope/portal/server/vegl/VGLJobStatusAndLogReader.java
- src/main/java/org/auscope/portal/server/web/controllers/JobListController.java
- src/main/resources/org/auscope/portal/server/web/controllers/vl-bootstrap.sh
- src/main/webapp/js/vegl/jobwizard/forms/DuplicateJobForm.js
- src/main/webapp/js/vegl/models/FileRecord.js
- src/main/webapp/js/vegl/preview/FilePreviewMixin.js
- src/main/webapp/js/vegl/preview/FilePreviewPanel.js
- src/main/webapp/js/vegl/preview/ImagePreview.js
- src/main/webapp/js/vegl/preview/LogPreview.js
- src/main/webapp/js/vegl/preview/PlainTextPreview.js
- src/main/webapp/js/vegl/widgets/JobFilesPanel.js
- src/test/java/org/auscope/portal/server/vegl/TestVGLJobStatusAndLogReader.java
- vm/vl.sh
The end user wishes to read logs as they are written (or at a regular interval), likewise some output files can be expected to be appended to/rewritten.
1) Make the intermediate logs visible (need work on backend/bootstrap scripts)
2) Make the file browser not completely clear on refresh
3) Add a refresh button to the preview for images
Also added:
* Logs now scroll to bottom by default
* "Internal files" are now hidden
If you want to test this before pulling, you will need to update config.properties vm.sh to point to this branch's version of vl.sh
> ANVGL-130 Intermediate log/output file previews

- src/main/java/org/auscope/portal/server/web/controllers/MenuController.java
Some unit tests under check for unix style line endings in some of the script files. These can fail under Windows if you have autocrlf setup. This file will force these "sensitive" files into Unix style
> Added gitattributes to force LF settings

- src/main/webapp/js/vegl/widgets/JobFilesPanel.js
Originally, changing job selection would clear the preview panel but it wouldn't clear the job selection.
> Anvgl 168   change job selection

- src/main/webapp/js/vegl/preview/TTLPreview.js
- src/main/webapp/js/vegl/widgets/JobDetailsPanel.js
TTL viewer, fixes display issues for TTL files. Will have a link at the top of the preview to the associated PROMS report if one exists, or a label stating that there is no report otherwise.
Requires the DB field:
`promsReportUrl` varchar(255) DEFAULT NULL,
> Anvgl 154   ttl preview

- vm/puppet/modules/visit/manifests/init.pp
The Visit 2.9.2 build_visit script has a number of failing links to packages. Upgrading to 2.11 fixes these links. Tested against the escript visit usage with no problems.
> Upgrade to Visit 2.11 due to failing resource links

- src/main/java/org/auscope/portal/server/web/controllers/BaseModelController.java
- src/main/java/org/auscope/portal/server/web/controllers/JobListController.java
- src/main/webapp/WEB-INF/jsp/joblist.jsp
- src/main/webapp/css/vl-styles.css
- src/main/webapp/js/vegl/models/AuditLog.js
- src/main/webapp/js/vegl/models/Job.js
- src/main/webapp/js/vegl/widgets/JobStatusWindow.js
- src/main/webapp/js/vegl/widgets/JobsTree.js
- src/test/java/org/auscope/portal/server/web/controllers/TestJobListController.java
Added a new status log browser that allows a user to browse a job's status change history (via the audit log) and the raw console log directly from a running compute instance (if available).
> VGL-183 Added a detailed Status Log viewer to jobs

- pom.xml
- src/main/java/org/auscope/portal/server/web/controllers/ScriptBuilderController.java
- src/main/java/org/auscope/portal/server/web/service/LintResult.java
- src/main/java/org/auscope/portal/server/web/service/TemplateLintService.java
- src/main/webapp/WEB-INF/jsp/jobbuilder.jsp
- src/main/webapp/js/ScriptBuilder/ScriptBuilder.js
- src/main/webapp/js/vegl/lint/pylint.js
- src/main/webapp/js/vegl/widgets/CodeEditorField.js
- src/test/java/org/auscope/portal/server/web/controllers/TestScriptBuilderController.java
Currently very verbose linting of the python template, including lots of convention and code smell checks. It also doesn't prevent you from continuing if it finds errors.
Requires pylint to be installed and available on the path for the webserver to execute.
N.B. Also includes an upgrade to jackson 2.8.5.
> VGL-181 template checking

- src/main/java/org/auscope/portal/core/services/cloud/CloudComputeServiceNci.java
Sometimes I think, for very old finished jobs, NCI will report that it can't find the job with that ID. Return MISSING now in this case.
> Better NCI job status checking. 

- src/main/java/org/auscope/portal/server/web/service/TemplateLintService.java
Tones down pylint checking so it ignores everything that's not a warning or error. Most usefully it ignores stylistic complaints, such as missing docstrings or trailing newlines.
> Vgl 181 pylint

- src/main/webapp/js/vegl/widgets/JobDetailsPanel.js
- src/main/webapp/js/vegl/widgets/JobFilesPanel.js
Re-enabled multi select file downloads for the job file panel. Explicitly blocks the user from combining download types for simplicity. We can always code in some (complicated) backend support if we want to remove this restriction.
> Re-enabled multi select file downloads

- src/main/webapp/js/vegl/widgets/search/FacetedCSWBrowserPanel.js
Switching registry will now:
1) Reset paging to initial state
2) abort any existing loading operation
This PR depends on https://github.com/AuScope/portal-core/pull/266
> VGL-213 Fixes paging/loading not resetting on reg change

- pom.xml
- src/main/java/org/auscope/portal/server/web/controllers/JobBuilderController.java
- src/main/java/org/auscope/portal/server/web/service/ScmEntryService.java
- src/test/java/org/auscope/portal/server/web/controllers/TestJobBuilderController.java
To support Raijin jobs:
* Update JobBuilderController and ScmEntryService to support retrieving compute services, toolboxes and images that are valid for a job without requiring that the job object is created and saved first.
* Update to use portal-core 2.1.0-SNAPSHOT
Minor fixes:
* Use /VGL-Portal context path in jetty run to align dev with default deployment
* Remove mygrid repo since it stopped working and we don't seem to need it anymore
> Devl 86 - support for raijin jobs

- src/main/java/org/auscope/portal/server/web/service/ScmEntryService.java
Hopefully final fix for DEVL-86. Now you can run a job that requires a run command on the toolbox (like escript).
> Include runcommand with machine image

- src/main/java/org/auscope/portal/server/vegl/VEGLJobManager.java
- src/main/java/org/auscope/portal/server/vegl/VglDownloadDao.java
- src/main/java/org/auscope/portal/server/web/controllers/JobBuilderController.java
- src/main/webapp/WEB-INF/applicationContext.xml
- src/test/java/org/auscope/portal/server/web/controllers/TestJobBuilderController.java
Fix for the duplicating job downloads. Now deletes existing job downloads from the database when replacing them with new ones.
> Devl 90 duplicate downloads

- src/main/java/org/auscope/portal/server/web/security/ANVGLGoogleOAuth2ServiceProperties.java
- src/main/webapp/WEB-INF/applicationContext-security.xml
Changed the Google sign in scope to combine both profile and email scopes so that the user's name would be returned with the user info once again. Should prevent Google login from crashing.
> Google sign in scope change

- src/main/java/org/auscope/portal/server/web/security/DefaultEntryPoint.java
- src/main/java/org/auscope/portal/server/web/security/RedirectUnconfiguredUserHandler.java
Fix "too many redirects" error when app loads up by not attempting to redirect to login when authorisation fails. Instead we catch the unauthorization error and send this response to the front-end to deal with.
> DEVL 131 - Too many redirects error on startup

- src/main/java/org/auscope/portal/server/web/controllers/JobBuilderController.java
- src/main/java/org/auscope/portal/server/web/service/ScmEntryService.java
Requires corresponding pull request in ngvl.
Fixes Aus 3326 and various other issues of the job wizard UI not updating correctly:
1) Added backend call `getComputeServicesForSolutions.do` to retrive the list of providers that can provide images for the given list of solutions
2) Fixed a potential NPE when `imageProviders.get(computeServiceId)` returns `null`
3) Fixed `getJobProviders(Collection<String> solutionIds, ANVGLUser user)` to return intersection of providers for the solutions rather than union. Previously if solution A only runs on Gadi and solution B only runs on AWS, both AWS and Gadi would be returned. No in this case empty result will be returned as there is no provider than can provide images for all solutions.
> Aus 3326 vgl offers aws compute provider even if solution does not support it
