src/main/java/org/auscope/portal/server/web/controllers/JobDownloadController.java
src/main/webapp/js/vegl/util/DataSelectionUtil.js
src/main/webapp/js/vegl/widgets/DataSelectionPanel.js
src/main/webapp/js/vegl/widgets/NetcdfSubsetPanel.js
src/main/webapp/jsimports.htm

Took the original NCSS work and extended it to make it a little more stable and useable.
See https://jira.csiro.au/browse/ANVGL-39

ANVGL-39 Port NetCDF Subset Service to ANVGL

---

src/main/webapp/WEB-INF/vl-known-layers.xml
src/main/webapp/js/vegl/Main-UI.js

ANVGL17: Change the order of knownLayers to be alphanumeric

Alphanumerical layer ordering

---

src/main/db/mysql/anvglportal_users.sql
src/main/java/org/auscope/portal/server/web/controllers/GeonetworkController.java
src/main/java/org/auscope/portal/server/web/controllers/JobBuilderController.java
src/main/java/org/auscope/portal/server/web/controllers/JobListController.java
src/main/java/org/auscope/portal/server/web/controllers/UserController.java
src/main/java/org/auscope/portal/server/web/security/ANVGLUser.java
src/main/java/org/auscope/portal/server/web/security/RedirectUnconfiguredUserHandler.java
src/main/resources/anvgluser.hbm.xml
src/main/resources/config.properties
src/main/resources/org/auscope/portal/server/web/controllers/vl-termsconditions.html
src/main/webapp/WEB-INF/applicationContext-security.xml
src/main/webapp/WEB-INF/jsp/page_header.jsp
src/main/webapp/WEB-INF/jsp/user.jsp
src/main/webapp/js/vegl/User-UI.js
src/main/webapp/js/vegl/models/ANVGLUser.js
src/main/webapp/js/vegl/widgets/ANVGLUserPanel.js
src/main/webapp/js/vegl/widgets/TermsConditionsWindow.js
src/test/java/org/auscope/portal/server/web/controllers/TestGeonetworkController.java
src/test/java/org/auscope/portal/server/web/controllers/TestJobBuilderController.java
src/test/java/org/auscope/portal/server/web/controllers/TestJobListController.java

See https://jira.csiro.au/browse/ANVGL-58

ANVGL-58 Basic user account GUI

---

src/main/db/mysql/anvglportal_users.sql
src/main/java/org/auscope/portal/server/web/controllers/UserController.java
src/main/java/org/auscope/portal/server/web/security/ANVGLUser.java
src/main/resources/anvgluser.hbm.xml
src/main/resources/org/auscope/portal/server/web/controllers/vl-cloudformation.json.tpl
src/main/webapp/WEB-INF/jsp/user.jsp
src/main/webapp/js/vegl/widgets/ANVGLUserPanel.js
src/main/webapp/js/vegl/widgets/CloudFormationTemplateWindow.js

Only basic popup for the time being.

ANVGL-56 Templating for cloud formation script

---

src/main/java/org/auscope/portal/server/web/controllers/BaseCloudController.java
src/main/java/org/auscope/portal/server/web/service/scm/Entries.java
src/main/java/org/auscope/portal/server/web/service/scm/Entry.java
src/main/java/org/auscope/portal/server/web/service/scm/Problem.java
src/main/java/org/auscope/portal/server/web/service/scm/Solution.java
src/main/java/org/auscope/portal/server/web/service/scm/Toolbox.java
src/main/resources/env.properties.default

Changed package imports to use Jackson 2.5.4
Some minor bug fixes and clean-up

Changed Jackson to version 2.5.4

---

.gitignore
src/main/java/org/auscope/portal/server/web/controllers/JobListController.java
src/main/webapp/js/vegl/JobBuilder.js
src/main/webapp/js/vegl/jobwizard/forms/JobObjectForm.js
src/main/webapp/js/vegl/jobwizard/forms/JobUploadForm.js
src/test/java/org/auscope/portal/server/web/controllers/TestJobListController.java

Removed job series from user workflow again (mostly reinstated Victor's changes from last year).
Removed job series form from the job submission workflow, so we start with the job upload form, which also creates the job object.

ANVGL-78: Remove series concept again

---

src/main/resources/org/auscope/portal/server/web/controllers/vl-cloudformation.json.tpl

Added wild card after bucket name to grant access to everything in the bucket as well

Fixes ANVGL-94

---

src/main/webapp/js/vegl/util/DataSelectionUtil.js
src/main/webapp/js/vegl/widgets/ErddapSubsetPanel.js
src/main/webapp/js/vegl/widgets/FileDownloadPanel.js
src/main/webapp/js/vegl/widgets/NetcdfSubsetPanel.js
src/main/webapp/js/vegl/widgets/WfsSubsetPanel.js

Got rid of default download directory as /tmp/ Moved it to /root (our working dir)

ANVGL-109 Moved download directory to working dir

---

src/main/webapp/js/vegl/JobList.js
src/main/webapp/js/vegl/widgets/JobsPanel.js

Added a simple task runner to periodically trigger job list refreshes (and status updates).
Added a simple check to stop multiple updates running (from the client side).

ANVGL-97 Added 60 second periodic job list refresh

---

src/main/webapp/js/vegl/JobList.js
src/main/webapp/js/vegl/widgets/JobDetailsPanel.js

Removed the over/under layout change at low width display. Now there's just a resizable splitter between log view and file view.

ANVGL-117 Simplified responsive layout to a resizable hbox

---

src/main/db/mysql/veglportal_jobs.sql
src/main/java/org/auscope/portal/server/vegl/VEGLJob.java
src/main/java/org/auscope/portal/server/web/controllers/JobBuilderController.java
src/main/resources/org/auscope/portal/server/web/controllers/vl-cloudformation.json.tpl
src/main/resources/vegljob.hbm.xml
src/main/webapp/js/vegl/jobwizard/forms/JobSubmitForm.js

Don't pull this until https://github.com/AuScope/portal-core/pull/184 gets pulled.
Adds a warning to job submission if the image being instanciated contains one or more persistent volumes.

ANVGL-120 Warning user about persistent volumes

---

src/main/webapp/js/vegl/jobwizard/forms/JobObjectForm.js
src/main/webapp/js/vegl/jobwizard/forms/JobUploadForm.js

Working again with latest changes to master.

Anvgl 113 - If no data selected, ask to continue once and go back if answer is no.

---

src/main/db/mysql/anvglportal_authorities.sql
src/main/db/mysql/anvglportal_job_solutions.sql
src/main/db/mysql/anvglportal_users.sql
src/main/db/mysql/veglportal_jobs.sql
src/main/db/mysql/veglportal_series.sql
src/main/db/mysql/vglportal_downloads.sql
src/main/db/mysql/vglportal_jobs_audit_log.sql
src/main/db/mysql/vglportal_parameters.sql
src/main/db/mysql/vglportal_signatures.sql

DB scripts updated: engine definitions removed and foreign key constraints added. Also some general clean up.

Solves ANVGL-90 and ANVGL-143

---

src/main/db/mysql/load.sh

Loads the SQL files with foreign key checking switched off, so we can load the tables in an arbitrary order.

Added mysql loader to handle table ordering

---

src/main/java/org/auscope/portal/server/web/service/ANVGLProvenanceService.java
src/main/java/org/auscope/portal/server/web/service/monitor/VGLJobStatusChangeHandler.java
src/test/java/org/auscope/portal/server/web/controllers/TestDownloadController.java
src/test/java/org/auscope/portal/server/web/service/ANVGLProvenanceServiceTest.java

Emergency fix. Cherry picked from Stu's master branch

Updated for new PROMS response object.

---

src/main/webapp/js/vegl/preview/PlainTextPreview.js

function PlainTextPreview#preview was missing parame…ter 'hash' in delcaration

Fixes ANVGL-158:

---

vm/puppet/escript.pp
vm/puppet/installPuppet-debian.sh
vm/puppet/modules/visit/manifests/init.pp
vm/puppet/modules/vl_common/manifests/init.pp

Fixed a number of dependency/build issues with the latest Debian Jessie image at NeCTAR

escript puppet updates for Debian Jessie

---

pom.xml
src/main/java/org/auscope/portal/server/vegl/VglDownload.java
src/main/java/org/auscope/portal/server/vegl/VglParameter.java
src/main/java/org/auscope/portal/server/web/controllers/AdminController.java
src/main/java/org/auscope/portal/server/web/controllers/GeonetworkController.java
src/main/java/org/auscope/portal/server/web/controllers/JobBuilderController.java
src/main/java/org/auscope/portal/server/web/controllers/JobListController.java
src/main/java/org/auscope/portal/server/web/controllers/MenuController.java
src/main/java/org/auscope/portal/server/web/controllers/OPeNDAPController.java
src/main/java/org/auscope/portal/server/web/controllers/ScriptBuilderController.java
src/main/java/org/auscope/portal/server/web/controllers/UserController.java
src/main/java/org/auscope/portal/server/web/interceptors/UserSessionInterceptor.java
src/main/java/org/auscope/portal/server/web/service/scm/Problem.java
src/main/java/org/auscope/portal/server/web/service/scm/Solution.java
src/main/resources/config.properties
src/main/webapp/WEB-INF/annotationsDispatcher-servlet.xml
src/main/webapp/WEB-INF/applicationContext-security.xml
src/main/webapp/WEB-INF/applicationContext.xml
src/main/webapp/WEB-INF/dispatcher-servlet.xml
src/main/webapp/WEB-INF/jsp/page_header.jsp
src/main/webapp/WEB-INF/profile-portal-production.xml
src/main/webapp/WEB-INF/profile-portal-test.xml
src/main/webapp/WEB-INF/views.xml
src/main/webapp/WEB-INF/vl-known-layers.xml
src/main/webapp/WEB-INF/vl-registries.xml
src/main/webapp/css/menu.css
src/main/webapp/js/vegl/models/Job.js
src/main/webapp/js/vegl/widgets/JobsTree.js
src/test/java/org/auscope/portal/server/web/controllers/TestCSWCacheController.java
src/test/java/org/auscope/portal/server/web/interceptors/TestUserSessionInterceptor.java

This will be required - https://github.com/AuScope/portal-core/pull/234
Upgrades spring IO platform to 2.0.8 to better align with portal-core. Numerous small tweaks to security code to support the new version.

Spring Security 4 - Full Support

---

src/main/webapp/WEB-INF/applicationContext-security.xml

Added <frame-options policy="SAMEORIGIN"/> to spring security http options

Fixed by allowing same origin frames

---

src/main/java/org/auscope/portal/core/services/cloud/CloudComputeServiceNci.java
src/main/java/org/auscope/portal/core/services/cloud/CloudStorageServiceNci.java
src/main/java/org/auscope/portal/core/services/cloud/SshCloudConnector.java
src/main/resources/org/auscope/portal/core/services/cloud/nci-download.job.tpl
src/main/resources/org/auscope/portal/core/services/cloud/nci-run.job.tpl
src/main/webapp/WEB-INF/jsp/joblist.jsp
src/main/webapp/js/vegl/jobwizard/forms/JobObjectForm.js

Main purpose of this PR is to add support for jobs that require more than 1 compute node (>16) processors. A few other minor fixes/improvements have also been included

VGLOPS-13 Raijin Support Round 2

---

src/main/java/org/auscope/portal/server/web/controllers/MenuController.java
src/main/java/org/auscope/portal/server/web/controllers/ScriptBuilderController.java
src/main/java/org/auscope/portal/server/web/service/TemplateLintService.java
src/main/webapp/WEB-INF/jsp/jobbuilder.jsp
src/main/webapp/js/vegl/lint/pylint.js
src/test/java/org/auscope/portal/server/web/controllers/TestMenuController.java

Client side ignores server errors when linting if the connection to the server succeeded, server logs errors as usual.
Also handles the case of finding no issues in the template properly!

VGL-181: Handle errors, and no lints(!), gracefully

---

src/main/java/org/auscope/portal/server/web/controllers/CSWSearchController.java

Expanding the metadata rewriting patterns to include two common mistakes.

Expanding MD rewrite pattern matching slightly

---

src/main/resources/config.properties
src/main/resources/org/auscope/portal/server/web/controllers/vl-termsconditions.html
src/main/webapp/WEB-INF/applicationContext-security.xml
src/main/webapp/js/vegl/jobwizard/forms/JobUploadForm.js

Also minor change to my dev machine config

Changed and removed some more references to ANVGL and GA.

---

src/main/db/mysql/anvgl.sql
src/main/java/org/auscope/portal/core/services/cloud/CloudComputeServiceNci.java
src/main/java/org/auscope/portal/server/vegl/VEGLJob.java
src/main/java/org/auscope/portal/server/web/controllers/JobBuilderController.java
src/main/java/org/auscope/portal/server/web/service/ScmEntryService.java
src/main/resources/vegljob.hbm.xml
src/main/webapp/js/vegl/jobwizard/forms/JobObjectForm.js
src/main/webapp/js/vegl/models/MachineImage.js
src/test/java/org/auscope/portal/server/web/controllers/TestJobBuilderController.java

Note- this adds a new column to the jobs table.

VGLOPS-31 Properly extracting run command from SSSC

---

src/main/java/org/auscope/portal/core/services/cloud/CloudComputeServiceNci.java
src/main/java/org/auscope/portal/server/web/controllers/JobBuilderController.java
src/test/java/org/auscope/portal/server/web/controllers/TestJobBuilderController.java

!!! Require updated portal-core with matching changes !!!
VM types are now filtered to only those meeting minimum image requirements.
https://jira.csiro.au/browse/VGL-196

Fixes VGL-196

---

src/main/java/org/auscope/portal/server/web/security/ANVGLUser.java

Renamed method isAcceptedTermsConditions so hibernate no longer thinks its a boolean

Fix VGL-208

---

src/main/java/org/auscope/portal/server/web/controllers/MenuController.java
src/main/java/org/auscope/portal/server/web/security/ANVGLUser.java
src/main/java/org/auscope/portal/server/web/security/RedirectUnconfiguredUserHandler.java
src/main/webapp/WEB-INF/jsp/notcs.jsp
src/test/java/org/auscope/portal/server/web/controllers/TestMenuController.java

There are now two error redirect pages. One for missing config (which has priority) and a "unaccepted terms and conditions" page.

VGL-210 Made unconfigured redirects more informative

---

pom.xml
src/main/java/org/auscope/portal/server/web/controllers/CSWSearchController.java
src/main/java/org/auscope/portal/server/web/service/LocalCSWFilterService.java
src/main/java/org/auscope/portal/server/web/service/csw/FacetedMultiSearchResponse.java
src/main/webapp/js/vegl/widgets/search/FacetedCSWBrowserPanel.js
src/main/webapp/js/vegl/widgets/search/FacetedSearchPanel.js
src/main/webapp/js/vegl/widgets/search/KeywordFacet.js
src/main/webapp/js/vegl/widgets/search/RegistryFacet.js
src/main/webapp/jsimports.htm
src/test/java/org/auscope/portal/server/web/controllers/TestCSWSearchController.java
src/test/java/org/auscope/portal/server/web/service/TestLocalCSWFilterService.java

Updated GUI and backend to support multiple CSW registry responses simultaneously.

VGL-217 Support for interleaving CSW Registries

---

src/main/java/org/auscope/portal/core/services/cloud/CloudComputeServiceNci.java
src/main/java/org/auscope/portal/server/web/service/ScmEntryService.java
src/main/java/org/auscope/portal/server/web/service/scm/Toolbox.java

Support HPC dependencies stored as an "image" for an HPC provider, consisting of a URL pointing to a PBS fragment.

Vgl 206 hpc modules

---

src/main/java/org/auscope/portal/server/web/service/TemplateLintService.java
src/main/webapp/WEB-INF/applicationContext.xml

Allow administrator to set pylint to be as finicky as they wish.

VGL-181 Make pylint command configurable

---

src/main/db/mysql/anvgl.sql
src/main/java/org/auscope/portal/server/vegl/VGLBookMark.java
src/main/java/org/auscope/portal/server/vegl/VGLBookMarkDao.java
src/main/java/org/auscope/portal/server/vegl/VGLBookMarkDownload.java
src/main/java/org/auscope/portal/server/vegl/VGLBookMarkDownloadDao.java
src/main/java/org/auscope/portal/server/web/controllers/BookMarksController.java
src/main/java/org/auscope/portal/server/web/controllers/CSWSearchController.java
src/main/java/org/auscope/portal/server/web/security/ANVGLUser.java
src/main/resources/anvgluser.hbm.xml
src/main/resources/config.properties
src/main/resources/vglbookmark.hbm.xml
src/main/resources/vglbookmarkdownload.hbm.xml
src/main/webapp/WEB-INF/applicationContext.xml

https://jira.csiro.au/browse/DEVL-55

Devl 55 bookmarks

---

pom.xml
src/main/java/org/auscope/portal/server/config/ProfilePortalProduction.java
src/main/java/org/auscope/portal/server/config/VglApplicationContext.java
src/main/java/org/auscope/portal/server/config/VlRegistries.java
src/main/java/org/auscope/portal/server/web/controllers/JobBuilderController.java
src/main/java/org/auscope/portal/server/web/controllers/JobListController.java
src/main/java/org/auscope/portal/server/web/controllers/MenuController.java
src/main/java/org/auscope/portal/server/web/controllers/UserController.java
src/main/java/org/auscope/portal/server/web/security/VEGLSecurityConfig.java
src/main/java/org/auscope/portal/server/web/security/aaf/AAFAuthenticationEntryPoint.java
src/main/java/org/auscope/portal/server/web/security/aaf/AAFAuthenticationFilter.java
src/main/java/org/auscope/portal/server/web/security/aaf/AAFAuthenticationRedirect.java
src/main/java/org/auscope/portal/server/web/security/aaf/JWTManagement.java
src/main/resources/application-registries.yaml
src/main/resources/application.yaml.default
src/test/java/org/auscope/portal/server/web/controllers/TestJobListController.java

* Fixed bug where Nectar EC2 access/secret keys were being used for Nectar storage.
* Registries now defined in application.yaml file.
* Some properties moved/renamed to e a bit more logical.

Fix Nectar key usage

---

src/main/resources/org/auscope/portal/core/services/cloud/nci-run.job.tpl
src/main/resources/org/auscope/portal/server/web/controllers/vl-provisioning.sh
vm/puppet/modules/vl_common/manifests/init.pp
vm/vl.sh

Provisioning updates should work on newer ubuntu images on all clouds.

Provisioning fix

---

.gitignore
pom.xml
src/main/db/mysql/anvgl.sql
src/main/java/org/auscope/portal/server/config/ProfilePortalProduction.java
src/main/java/org/auscope/portal/server/config/VglApplicationContext.java
src/main/java/org/auscope/portal/server/config/VlRegistries.java
src/main/java/org/auscope/portal/server/vegl/VEGLJob.java
src/main/java/org/auscope/portal/server/vegl/VEGLJobManager.java
src/main/java/org/auscope/portal/server/vegl/VGLDataPurchase.java
src/main/java/org/auscope/portal/server/vegl/VGLJobPurchase.java
src/main/java/org/auscope/portal/server/web/controllers/JobBuilderController.java
src/main/java/org/auscope/portal/server/web/controllers/JobDownloadController.java
src/main/java/org/auscope/portal/server/web/controllers/PurchaseController.java
src/main/java/org/auscope/portal/server/web/repositories/VGLDataPurchaseRepository.java
src/main/java/org/auscope/portal/server/web/repositories/VGLJobPurchaseRepository.java
src/main/java/org/auscope/portal/server/web/service/VGLPurchaseService.java
src/main/resources/application-registries.yaml
src/main/resources/application.yaml.default
src/test/java/org/auscope/portal/server/web/controllers/TestJobDownloadController.java
src/test/java/org/auscope/portal/server/web/controllers/TestPurchaseController.java

Changes from DCDP updated for current master.
Requires matching change in portal-core: https://github.com/AuScope/portal-core/pull/360
Most of the changes relate to bookmarks and purchases, which are not reflected in the current front-end. These do not have visible functionality to test yet, just ensure they do not cause problems with the current VGL functionality.

Review dcdp 62
